### ISSUE TITLE
Triple Sum in An array 

### ISSUE THREAD

**Issue by tannishk** [tannishk/competitive#12]
I have given the solution in python kindly try to implement it in different languages . Feel Free to alter my solution if you find them not upto the mark 

[https://github.com/tannishk/competitive/blob/master/questions/triple-sum-in-array.txt](url)

**Comment by Pratik151** [comment]
@tannishk Hey I will try this in C and Java. Can we make PR for other questions also in other languages?

**Comment by tannishk** [comment]
@Pratik151 : Sure . Yes you absolutely can . Thanks for your Help

**Comment by SergiSMJ** [comment]
When you say triple sum in an array you mean a function that calculates the greatest sum of 3 consecutive numbers?

**Comment by palnabarun** [comment]
Can I attempt in C++?

**Comment by SergiSMJ** [comment]
I added a solution in Javascript :)
